# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id', '-timestamp', '-updated']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
