# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default=datetime.datetime(2016, 11, 21, 17, 36, 24, 237787, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
